/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PartyId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const PartyVisitRecord = IDL.Record({
  'comment' : IDL.Text,
  'paymentDate' : Time,
  'amount' : IDL.Int,
  'nextPaymentDate' : IDL.Opt(Time),
  'location' : IDL.Opt(Location),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ShopBranding = IDL.Record({
  'logo' : IDL.Opt(ExternalBlob),
  'name' : IDL.Opt(IDL.Text),
});
export const Party = IDL.Record({
  'id' : PartyId,
  'pan' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'dueAmount' : IDL.Int,
});
export const UpgradeData = IDL.Record({
  'partyVisitRecords' : IDL.Vec(IDL.Tuple(PartyId, IDL.Vec(PartyVisitRecord))),
  'branding' : IDL.Opt(ShopBranding),
  'parties' : IDL.Vec(IDL.Tuple(PartyId, Party)),
});
export const TimeConstraint = IDL.Variant({
  'after' : Time,
  'before' : Time,
  'equals' : Time,
});
export const TextConstraint = IDL.Variant({
  'contains' : IDL.Text,
  'greaterThan' : IDL.Text,
  'equals' : IDL.Text,
  'lessThan' : IDL.Text,
});
export const LocationConstraint = IDL.Variant({
  'greaterLatitude' : IDL.Float64,
  'greaterLongitude' : IDL.Float64,
  'withinRadius' : IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64),
  'lessLatitude' : IDL.Float64,
  'lessLongitude' : IDL.Float64,
});
export const IntConstraint = IDL.Variant({
  'greaterThan' : IDL.Int,
  'equals' : IDL.Int,
  'lessThan' : IDL.Int,
});
export const PartyVisitRecordFilter = IDL.Record({
  'paymentDateFilter' : IDL.Opt(TimeConstraint),
  'nextPaymentDateFilter' : IDL.Opt(TimeConstraint),
  'commentFilter' : IDL.Opt(TextConstraint),
  'locationFilter' : IDL.Opt(LocationConstraint),
  'amountFilter' : IDL.Opt(IntConstraint),
});
export const PaymentId = IDL.Text;
export const VisitRecordMetadata = IDL.Record({
  'paymentId' : PaymentId,
  'hasLocation' : IDL.Bool,
  'hasNextPaymentDate' : IDL.Bool,
});
export const AggregateVisitRecordMetadata = IDL.Record({
  'filteredPaymentsMetadata' : IDL.Vec(VisitRecordMetadata),
  'allPaymentsMetadata' : IDL.Vec(VisitRecordMetadata),
});
export const StaffAccount = IDL.Record({
  'boundPrincipal' : IDL.Opt(IDL.Principal),
  'loginName' : IDL.Text,
  'canViewAllRecords' : IDL.Bool,
  'isDisabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addParty' : IDL.Func(
      [PartyId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateStaff' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'clearLogs' : IDL.Func([], [], []),
  'createStaffAccount' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'deleteParty' : IDL.Func([PartyId], [], []),
  'disableStaffAccount' : IDL.Func([IDL.Text], [], []),
  'exportUpgradeData' : IDL.Func([], [UpgradeData], ['query']),
  'filterPartyVisitRecordMetadata' : IDL.Func(
      [PartyId, PartyVisitRecordFilter],
      [AggregateVisitRecordMetadata],
      ['query'],
    ),
  'filterPartyVisitRecords' : IDL.Func(
      [PartyId, PartyVisitRecordFilter],
      [IDL.Vec(IDL.Tuple(PaymentId, PartyVisitRecord))],
      ['query'],
    ),
  'generatePartyId' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getAllParties' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Party))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'name' : IDL.Text }))],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLogs' : IDL.Func([], [IDL.Vec(IDL.Tuple(Time, IDL.Text))], ['query']),
  'getParty' : IDL.Func(
      [PartyId],
      [
        IDL.Opt(
          IDL.Record({
            'pan' : IDL.Text,
            'name' : IDL.Text,
            'address' : IDL.Text,
            'phone' : IDL.Text,
            'dueAmount' : IDL.Int,
          })
        ),
      ],
      ['query'],
    ),
  'getPartyIdTest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
  'getPartyVisitRecordMetadata' : IDL.Func(
      [PartyId],
      [IDL.Vec(VisitRecordMetadata)],
      ['query'],
    ),
  'getPartyVisitRecords' : IDL.Func(
      [PartyId],
      [IDL.Vec(IDL.Tuple(PaymentId, PartyVisitRecord))],
      ['query'],
    ),
  'getShopBranding' : IDL.Func([], [IDL.Opt(ShopBranding)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Record({ 'name' : IDL.Text }))],
      ['query'],
    ),
  'importUpgradeData' : IDL.Func([UpgradeData], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listStaffAccounts' : IDL.Func([], [IDL.Vec(StaffAccount)], ['query']),
  'recordPartyVisit' : IDL.Func(
      [PartyId, IDL.Int, IDL.Text, Time, IDL.Opt(Time), IDL.Opt(Location)],
      [IDL.Text],
      [],
    ),
  'recordPayment' : IDL.Func(
      [PartyId, IDL.Int, IDL.Text, Time, IDL.Opt(Time)],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Record({ 'name' : IDL.Text })],
      [],
      [],
    ),
  'setShopBranding' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateParty' : IDL.Func(
      [PartyId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'updateStaffAccount' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Bool), IDL.Opt(IDL.Bool)],
      [],
      [],
    ),
  'validateAndGenerateNewPartyId' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PartyId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const PartyVisitRecord = IDL.Record({
    'comment' : IDL.Text,
    'paymentDate' : Time,
    'amount' : IDL.Int,
    'nextPaymentDate' : IDL.Opt(Time),
    'location' : IDL.Opt(Location),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ShopBranding = IDL.Record({
    'logo' : IDL.Opt(ExternalBlob),
    'name' : IDL.Opt(IDL.Text),
  });
  const Party = IDL.Record({
    'id' : PartyId,
    'pan' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'dueAmount' : IDL.Int,
  });
  const UpgradeData = IDL.Record({
    'partyVisitRecords' : IDL.Vec(
      IDL.Tuple(PartyId, IDL.Vec(PartyVisitRecord))
    ),
    'branding' : IDL.Opt(ShopBranding),
    'parties' : IDL.Vec(IDL.Tuple(PartyId, Party)),
  });
  const TimeConstraint = IDL.Variant({
    'after' : Time,
    'before' : Time,
    'equals' : Time,
  });
  const TextConstraint = IDL.Variant({
    'contains' : IDL.Text,
    'greaterThan' : IDL.Text,
    'equals' : IDL.Text,
    'lessThan' : IDL.Text,
  });
  const LocationConstraint = IDL.Variant({
    'greaterLatitude' : IDL.Float64,
    'greaterLongitude' : IDL.Float64,
    'withinRadius' : IDL.Tuple(IDL.Float64, IDL.Float64, IDL.Float64),
    'lessLatitude' : IDL.Float64,
    'lessLongitude' : IDL.Float64,
  });
  const IntConstraint = IDL.Variant({
    'greaterThan' : IDL.Int,
    'equals' : IDL.Int,
    'lessThan' : IDL.Int,
  });
  const PartyVisitRecordFilter = IDL.Record({
    'paymentDateFilter' : IDL.Opt(TimeConstraint),
    'nextPaymentDateFilter' : IDL.Opt(TimeConstraint),
    'commentFilter' : IDL.Opt(TextConstraint),
    'locationFilter' : IDL.Opt(LocationConstraint),
    'amountFilter' : IDL.Opt(IntConstraint),
  });
  const PaymentId = IDL.Text;
  const VisitRecordMetadata = IDL.Record({
    'paymentId' : PaymentId,
    'hasLocation' : IDL.Bool,
    'hasNextPaymentDate' : IDL.Bool,
  });
  const AggregateVisitRecordMetadata = IDL.Record({
    'filteredPaymentsMetadata' : IDL.Vec(VisitRecordMetadata),
    'allPaymentsMetadata' : IDL.Vec(VisitRecordMetadata),
  });
  const StaffAccount = IDL.Record({
    'boundPrincipal' : IDL.Opt(IDL.Principal),
    'loginName' : IDL.Text,
    'canViewAllRecords' : IDL.Bool,
    'isDisabled' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addParty' : IDL.Func(
        [PartyId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateStaff' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'clearLogs' : IDL.Func([], [], []),
    'createStaffAccount' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'deleteParty' : IDL.Func([PartyId], [], []),
    'disableStaffAccount' : IDL.Func([IDL.Text], [], []),
    'exportUpgradeData' : IDL.Func([], [UpgradeData], ['query']),
    'filterPartyVisitRecordMetadata' : IDL.Func(
        [PartyId, PartyVisitRecordFilter],
        [AggregateVisitRecordMetadata],
        ['query'],
      ),
    'filterPartyVisitRecords' : IDL.Func(
        [PartyId, PartyVisitRecordFilter],
        [IDL.Vec(IDL.Tuple(PaymentId, PartyVisitRecord))],
        ['query'],
      ),
    'generatePartyId' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getAllParties' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Party))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'name' : IDL.Text }))],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLogs' : IDL.Func([], [IDL.Vec(IDL.Tuple(Time, IDL.Text))], ['query']),
    'getParty' : IDL.Func(
        [PartyId],
        [
          IDL.Opt(
            IDL.Record({
              'pan' : IDL.Text,
              'name' : IDL.Text,
              'address' : IDL.Text,
              'phone' : IDL.Text,
              'dueAmount' : IDL.Int,
            })
          ),
        ],
        ['query'],
      ),
    'getPartyIdTest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
    'getPartyVisitRecordMetadata' : IDL.Func(
        [PartyId],
        [IDL.Vec(VisitRecordMetadata)],
        ['query'],
      ),
    'getPartyVisitRecords' : IDL.Func(
        [PartyId],
        [IDL.Vec(IDL.Tuple(PaymentId, PartyVisitRecord))],
        ['query'],
      ),
    'getShopBranding' : IDL.Func([], [IDL.Opt(ShopBranding)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Record({ 'name' : IDL.Text }))],
        ['query'],
      ),
    'importUpgradeData' : IDL.Func([UpgradeData], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listStaffAccounts' : IDL.Func([], [IDL.Vec(StaffAccount)], ['query']),
    'recordPartyVisit' : IDL.Func(
        [PartyId, IDL.Int, IDL.Text, Time, IDL.Opt(Time), IDL.Opt(Location)],
        [IDL.Text],
        [],
      ),
    'recordPayment' : IDL.Func(
        [PartyId, IDL.Int, IDL.Text, Time, IDL.Opt(Time)],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Record({ 'name' : IDL.Text })],
        [],
        [],
      ),
    'setShopBranding' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateParty' : IDL.Func(
        [PartyId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'updateStaffAccount' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Bool), IDL.Opt(IDL.Bool)],
        [],
        [],
      ),
    'validateAndGenerateNewPartyId' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };