/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AggregateVisitRecordMetadata {
  'filteredPaymentsMetadata' : Array<VisitRecordMetadata>,
  'allPaymentsMetadata' : Array<VisitRecordMetadata>,
}
export type ExternalBlob = Uint8Array;
export type IntConstraint = { 'greaterThan' : bigint } |
  { 'equals' : bigint } |
  { 'lessThan' : bigint };
export interface Location { 'latitude' : number, 'longitude' : number }
export type LocationConstraint = { 'greaterLatitude' : number } |
  { 'greaterLongitude' : number } |
  { 'withinRadius' : [number, number, number] } |
  { 'lessLatitude' : number } |
  { 'lessLongitude' : number };
export interface PaginatedPartyVisitRecordResponse {
  'nextOffset' : bigint,
  'records' : Array<[string, PartyVisitRecord]>,
  'totalRecords' : bigint,
}
export interface Party {
  'id' : PartyId,
  'pan' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
  'dueAmount' : bigint,
}
export type PartyId = string;
export interface PartyVisitRecord {
  'comment' : string,
  'paymentDate' : Time,
  'amount' : bigint,
  'nextPaymentDate' : [] | [Time],
  'location' : [] | [Location],
}
export interface PartyVisitRecordFilter {
  'paymentDateFilter' : [] | [TimeConstraint],
  'nextPaymentDateFilter' : [] | [TimeConstraint],
  'commentFilter' : [] | [TextConstraint],
  'locationFilter' : [] | [LocationConstraint],
  'amountFilter' : [] | [IntConstraint],
}
export type PaymentId = string;
export interface ShopBranding {
  'logo' : [] | [ExternalBlob],
  'name' : [] | [string],
}
export type TextConstraint = { 'contains' : string } |
  { 'greaterThan' : string } |
  { 'equals' : string } |
  { 'lessThan' : string };
export type Time = bigint;
export type TimeConstraint = { 'after' : Time } |
  { 'before' : Time } |
  { 'equals' : Time };
export interface UpgradeData {
  'partyVisitRecords' : Array<[PartyId, Array<PartyVisitRecord>]>,
  'branding' : [] | [ShopBranding],
  'parties' : Array<[PartyId, Party]>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitRecordMetadata {
  'paymentId' : PaymentId,
  'hasLocation' : boolean,
  'hasNextPaymentDate' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addParty' : ActorMethod<
    [PartyId, string, string, string, string, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearLogs' : ActorMethod<[], undefined>,
  'deleteParty' : ActorMethod<[PartyId], undefined>,
  'exportUpgradeData' : ActorMethod<[], UpgradeData>,
  'filterPartyVisitRecordMetadata' : ActorMethod<
    [PartyId, PartyVisitRecordFilter],
    AggregateVisitRecordMetadata
  >,
  'filterPartyVisitRecords' : ActorMethod<
    [PartyId, PartyVisitRecordFilter],
    Array<[PaymentId, PartyVisitRecord]>
  >,
  'getAllParties' : ActorMethod<[], Array<[string, Party]>>,
  'getAllPartiesWithVisitRecords' : ActorMethod<
    [],
    Array<[string, Party, Array<PartyVisitRecord>]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLogs' : ActorMethod<[], Array<[Time, string]>>,
  'getPartiesWithTodayDuePayments' : ActorMethod<
    [],
    Array<[PartyId, Array<PartyVisitRecord>]>
  >,
  'getParty' : ActorMethod<
    [PartyId],
    [] | [
      {
        'pan' : string,
        'name' : string,
        'address' : string,
        'phone' : string,
        'dueAmount' : bigint,
      }
    ]
  >,
  'getPartyIdTest' : ActorMethod<[string, string], string>,
  'getPartyVisitRecordMetadata' : ActorMethod<
    [PartyId],
    Array<VisitRecordMetadata>
  >,
  'getPartyVisitRecords' : ActorMethod<
    [PartyId],
    Array<[PaymentId, PartyVisitRecord]>
  >,
  'getShopBranding' : ActorMethod<[], [] | [ShopBranding]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importUpgradeData' : ActorMethod<[UpgradeData], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logError' : ActorMethod<[string], undefined>,
  'paginatedPartyVisitRecords' : ActorMethod<
    [PartyId, bigint, bigint],
    PaginatedPartyVisitRecordResponse
  >,
  'recordPartyVisit' : ActorMethod<
    [PartyId, bigint, string, Time, [] | [Time], [] | [Location]],
    string
  >,
  'recordPayment' : ActorMethod<
    [PartyId, bigint, string, Time, [] | [Time]],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setShopBranding' : ActorMethod<
    [[] | [string], [] | [ExternalBlob]],
    undefined
  >,
  'updateParty' : ActorMethod<
    [PartyId, string, string, string, string, bigint],
    undefined
  >,
  'validateAndGenerateNewPartyId' : ActorMethod<[string, string], string>,
  'validateAndGeneratePartyId' : ActorMethod<[string, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];