/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    longitude: number;
}
export interface ShopBranding {
    logo?: ExternalBlob;
    name?: string;
}
export type Time = bigint;
export type TextConstraint = {
    __kind__: "contains";
    contains: string;
} | {
    __kind__: "greaterThan";
    greaterThan: string;
} | {
    __kind__: "equals";
    equals: string;
} | {
    __kind__: "lessThan";
    lessThan: string;
};
export type IntConstraint = {
    __kind__: "greaterThan";
    greaterThan: bigint;
} | {
    __kind__: "equals";
    equals: bigint;
} | {
    __kind__: "lessThan";
    lessThan: bigint;
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PartyVisitRecord {
    comment: string;
    paymentDate: Time;
    amount: bigint;
    nextPaymentDate?: Time;
    location?: Location;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type LocationConstraint = {
    __kind__: "greaterLatitude";
    greaterLatitude: number;
} | {
    __kind__: "greaterLongitude";
    greaterLongitude: number;
} | {
    __kind__: "withinRadius";
    withinRadius: [number, number, number];
} | {
    __kind__: "lessLatitude";
    lessLatitude: number;
} | {
    __kind__: "lessLongitude";
    lessLongitude: number;
};
export interface UpgradeData {
    partyVisitRecords: Array<[PartyId, Array<PartyVisitRecord>]>;
    branding?: ShopBranding;
    parties: Array<[PartyId, Party]>;
}
export type TimeConstraint = {
    __kind__: "after";
    after: Time;
} | {
    __kind__: "before";
    before: Time;
} | {
    __kind__: "equals";
    equals: Time;
};
export type PaymentId = string;
export interface PartyVisitRecordFilter {
    paymentDateFilter?: TimeConstraint;
    nextPaymentDateFilter?: TimeConstraint;
    commentFilter?: TextConstraint;
    locationFilter?: LocationConstraint;
    amountFilter?: IntConstraint;
}
export type PartyId = string;
export interface Party {
    id: PartyId;
    pan: string;
    name: string;
    address: string;
    phone: string;
    dueAmount: bigint;
}
export interface VisitRecordMetadata {
    paymentId: PaymentId;
    hasLocation: boolean;
    hasNextPaymentDate: boolean;
}
export interface AggregateVisitRecordMetadata {
    filteredPaymentsMetadata: Array<VisitRecordMetadata>;
    allPaymentsMetadata: Array<VisitRecordMetadata>;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addParty(partyId: PartyId, name: string, address: string, phone: string, pan: string, dueAmount: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearLogs(): Promise<void>;
    deleteParty(partyId: PartyId): Promise<void>;
    exportUpgradeData(): Promise<UpgradeData>;
    filterPartyVisitRecordMetadata(partyId: PartyId, _filter: PartyVisitRecordFilter): Promise<AggregateVisitRecordMetadata>;
    filterPartyVisitRecords(partyId: PartyId, _filter: PartyVisitRecordFilter): Promise<Array<[PaymentId, PartyVisitRecord]>>;
    getAllParties(): Promise<Array<[string, Party]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLogs(): Promise<Array<[Time, string]>>;
    getParty(_id: PartyId): Promise<{
        pan: string;
        name: string;
        address: string;
        phone: string;
        dueAmount: bigint;
    } | null>;
    getPartyIdTest(name: string, phone: string): Promise<string>;
    getPartyVisitRecordMetadata(partyId: PartyId): Promise<Array<VisitRecordMetadata>>;
    getPartyVisitRecords(partyId: PartyId): Promise<Array<[PaymentId, PartyVisitRecord]>>;
    getShopBranding(): Promise<ShopBranding | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importUpgradeData(data: UpgradeData): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    logError(message: string): Promise<void>;
    recordPartyVisit(partyId: PartyId, amount: bigint, comment: string, paymentDate: Time, nextPayment: Time | null, location: Location | null): Promise<string>;
    recordPayment(partyId: PartyId, amount: bigint, comment: string, paymentDate: Time, nextPayment: Time | null): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setShopBranding(name: string | null, logo: ExternalBlob | null): Promise<void>;
    updateParty(partyId: PartyId, name: string, address: string, phoneNumber: string, pan: string, dueAmount: bigint): Promise<void>;
    validateAndGenerateNewPartyId(name: string, phone: string): Promise<string>;
    validateAndGeneratePartyId(name: string, phone: string): Promise<string>;
}
import type { ExternalBlob as _ExternalBlob, IntConstraint as _IntConstraint, Location as _Location, LocationConstraint as _LocationConstraint, Party as _Party, PartyId as _PartyId, PartyVisitRecord as _PartyVisitRecord, PartyVisitRecordFilter as _PartyVisitRecordFilter, PaymentId as _PaymentId, ShopBranding as _ShopBranding, TextConstraint as _TextConstraint, Time as _Time, TimeConstraint as _TimeConstraint, UpgradeData as _UpgradeData, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addParty(arg0: PartyId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addParty(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addParty(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearLogs(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearLogs();
            return result;
        }
    }
    async deleteParty(arg0: PartyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteParty(arg0);
            return result;
        }
    }
    async exportUpgradeData(): Promise<UpgradeData> {
        if (this.processError) {
            try {
                const result = await this.actor.exportUpgradeData();
                return from_candid_UpgradeData_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportUpgradeData();
            return from_candid_UpgradeData_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterPartyVisitRecordMetadata(arg0: PartyId, arg1: PartyVisitRecordFilter): Promise<AggregateVisitRecordMetadata> {
        if (this.processError) {
            try {
                const result = await this.actor.filterPartyVisitRecordMetadata(arg0, to_candid_PartyVisitRecordFilter_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterPartyVisitRecordMetadata(arg0, to_candid_PartyVisitRecordFilter_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async filterPartyVisitRecords(arg0: PartyId, arg1: PartyVisitRecordFilter): Promise<Array<[PaymentId, PartyVisitRecord]>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterPartyVisitRecords(arg0, to_candid_PartyVisitRecordFilter_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterPartyVisitRecords(arg0, to_candid_PartyVisitRecordFilter_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllParties(): Promise<Array<[string, Party]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParties();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParties();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogs(): Promise<Array<[Time, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogs();
            return result;
        }
    }
    async getParty(arg0: PartyId): Promise<{
        pan: string;
        name: string;
        address: string;
        phone: string;
        dueAmount: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getParty(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParty(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartyIdTest(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartyIdTest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartyIdTest(arg0, arg1);
            return result;
        }
    }
    async getPartyVisitRecordMetadata(arg0: PartyId): Promise<Array<VisitRecordMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartyVisitRecordMetadata(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartyVisitRecordMetadata(arg0);
            return result;
        }
    }
    async getPartyVisitRecords(arg0: PartyId): Promise<Array<[PaymentId, PartyVisitRecord]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartyVisitRecords(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartyVisitRecords(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShopBranding(): Promise<ShopBranding | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopBranding();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopBranding();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async importUpgradeData(arg0: UpgradeData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importUpgradeData(await to_candid_UpgradeData_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importUpgradeData(await to_candid_UpgradeData_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logError(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logError(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logError(arg0);
            return result;
        }
    }
    async recordPartyVisit(arg0: PartyId, arg1: bigint, arg2: string, arg3: Time, arg4: Time | null, arg5: Location | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPartyVisit(arg0, arg1, arg2, arg3, to_candid_opt_n51(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPartyVisit(arg0, arg1, arg2, arg3, to_candid_opt_n51(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async recordPayment(arg0: PartyId, arg1: bigint, arg2: string, arg3: Time, arg4: Time | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(arg0, arg1, arg2, arg3, to_candid_opt_n51(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(arg0, arg1, arg2, arg3, to_candid_opt_n51(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setShopBranding(arg0: string | null, arg1: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setShopBranding(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), await to_candid_opt_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setShopBranding(to_candid_opt_n53(this._uploadFile, this._downloadFile, arg0), await to_candid_opt_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateParty(arg0: PartyId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParty(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParty(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async validateAndGenerateNewPartyId(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAndGenerateNewPartyId(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAndGenerateNewPartyId(arg0, arg1);
            return result;
        }
    }
    async validateAndGeneratePartyId(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAndGeneratePartyId(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAndGeneratePartyId(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PartyVisitRecord_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartyVisitRecord): PartyVisitRecord {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_ShopBranding_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShopBranding): Promise<ShopBranding> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_UpgradeData_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpgradeData): Promise<UpgradeData> {
    return await from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShopBranding]): Promise<ShopBranding | null> {
    return value.length === 0 ? null : await from_candid_ShopBranding_n20(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        pan: string;
        name: string;
        address: string;
        phone: string;
        dueAmount: bigint;
    }]): {
    pan: string;
    name: string;
    address: string;
    phone: string;
    dueAmount: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    partyVisitRecords: Array<[_PartyId, Array<_PartyVisitRecord>]>;
    branding: [] | [_ShopBranding];
    parties: Array<[_PartyId, _Party]>;
}): Promise<{
    partyVisitRecords: Array<[PartyId, Array<PartyVisitRecord>]>;
    branding?: ShopBranding;
    parties: Array<[PartyId, Party]>;
}> {
    return {
        partyVisitRecords: from_candid_vec_n12(_uploadFile, _downloadFile, value.partyVisitRecords),
        branding: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.branding)),
        parties: value.parties
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    comment: string;
    paymentDate: _Time;
    amount: bigint;
    nextPaymentDate: [] | [_Time];
    location: [] | [_Location];
}): {
    comment: string;
    paymentDate: Time;
    amount: bigint;
    nextPaymentDate?: Time;
    location?: Location;
} {
    return {
        comment: value.comment,
        paymentDate: value.paymentDate,
        amount: value.amount,
        nextPaymentDate: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.nextPaymentDate)),
        location: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.location))
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logo: [] | [_ExternalBlob];
    name: [] | [string];
}): Promise<{
    logo?: ExternalBlob;
    name?: string;
}> {
    return {
        logo: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.logo)),
        name: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.name))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_PartyId, Array<_PartyVisitRecord>]): [PartyId, Array<PartyVisitRecord>] {
    return [
        value[0],
        from_candid_vec_n14(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_PaymentId, _PartyVisitRecord]): [PaymentId, PartyVisitRecord] {
    return [
        value[0],
        from_candid_PartyVisitRecord_n15(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_PartyId, Array<_PartyVisitRecord>]>): Array<[PartyId, Array<PartyVisitRecord>]> {
    return value.map((x)=>from_candid_tuple_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PartyVisitRecord>): Array<PartyVisitRecord> {
    return value.map((x)=>from_candid_PartyVisitRecord_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_PaymentId, _PartyVisitRecord]>): Array<[PaymentId, PartyVisitRecord]> {
    return value.map((x)=>from_candid_tuple_n36(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_IntConstraint_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IntConstraint): _IntConstraint {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_LocationConstraint_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocationConstraint): _LocationConstraint {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_PartyVisitRecordFilter_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartyVisitRecordFilter): _PartyVisitRecordFilter {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_PartyVisitRecord_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartyVisitRecord): _PartyVisitRecord {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_ShopBranding_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShopBranding): Promise<_ShopBranding> {
    return await to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_TextConstraint_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TextConstraint): _TextConstraint {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_TimeConstraint_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeConstraint): _TimeConstraint {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
async function to_candid_UpgradeData_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpgradeData): Promise<_UpgradeData> {
    return await to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Location | null): [] | [_Location] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n50(_uploadFile, _downloadFile, value));
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentDateFilter?: TimeConstraint;
    nextPaymentDateFilter?: TimeConstraint;
    commentFilter?: TextConstraint;
    locationFilter?: LocationConstraint;
    amountFilter?: IntConstraint;
}): {
    paymentDateFilter: [] | [_TimeConstraint];
    nextPaymentDateFilter: [] | [_TimeConstraint];
    commentFilter: [] | [_TextConstraint];
    locationFilter: [] | [_LocationConstraint];
    amountFilter: [] | [_IntConstraint];
} {
    return {
        paymentDateFilter: value.paymentDateFilter ? candid_some(to_candid_TimeConstraint_n27(_uploadFile, _downloadFile, value.paymentDateFilter)) : candid_none(),
        nextPaymentDateFilter: value.nextPaymentDateFilter ? candid_some(to_candid_TimeConstraint_n27(_uploadFile, _downloadFile, value.nextPaymentDateFilter)) : candid_none(),
        commentFilter: value.commentFilter ? candid_some(to_candid_TextConstraint_n29(_uploadFile, _downloadFile, value.commentFilter)) : candid_none(),
        locationFilter: value.locationFilter ? candid_some(to_candid_LocationConstraint_n31(_uploadFile, _downloadFile, value.locationFilter)) : candid_none(),
        amountFilter: value.amountFilter ? candid_some(to_candid_IntConstraint_n33(_uploadFile, _downloadFile, value.amountFilter)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    partyVisitRecords: Array<[PartyId, Array<PartyVisitRecord>]>;
    branding?: ShopBranding;
    parties: Array<[PartyId, Party]>;
}): Promise<{
    partyVisitRecords: Array<[_PartyId, Array<_PartyVisitRecord>]>;
    branding: [] | [_ShopBranding];
    parties: Array<[_PartyId, _Party]>;
}> {
    return {
        partyVisitRecords: to_candid_vec_n43(_uploadFile, _downloadFile, value.partyVisitRecords),
        branding: value.branding ? candid_some(await to_candid_ShopBranding_n48(_uploadFile, _downloadFile, value.branding)) : candid_none(),
        parties: value.parties
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    comment: string;
    paymentDate: Time;
    amount: bigint;
    nextPaymentDate?: Time;
    location?: Location;
}): {
    comment: string;
    paymentDate: _Time;
    amount: bigint;
    nextPaymentDate: [] | [_Time];
    location: [] | [_Location];
} {
    return {
        comment: value.comment,
        paymentDate: value.paymentDate,
        amount: value.amount,
        nextPaymentDate: value.nextPaymentDate ? candid_some(value.nextPaymentDate) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
async function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logo?: ExternalBlob;
    name?: string;
}): Promise<{
    logo: [] | [_ExternalBlob];
    name: [] | [string];
}> {
    return {
        logo: value.logo ? candid_some(await to_candid_ExternalBlob_n50(_uploadFile, _downloadFile, value.logo)) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none()
    };
}
function to_candid_tuple_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [PartyId, Array<PartyVisitRecord>]): [_PartyId, Array<_PartyVisitRecord>] {
    return [
        value[0],
        to_candid_vec_n45(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "after";
    after: Time;
} | {
    __kind__: "before";
    before: Time;
} | {
    __kind__: "equals";
    equals: Time;
}): {
    after: _Time;
} | {
    before: _Time;
} | {
    equals: _Time;
} {
    return value.__kind__ === "after" ? {
        after: value.after
    } : value.__kind__ === "before" ? {
        before: value.before
    } : value.__kind__ === "equals" ? {
        equals: value.equals
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "contains";
    contains: string;
} | {
    __kind__: "greaterThan";
    greaterThan: string;
} | {
    __kind__: "equals";
    equals: string;
} | {
    __kind__: "lessThan";
    lessThan: string;
}): {
    contains: string;
} | {
    greaterThan: string;
} | {
    equals: string;
} | {
    lessThan: string;
} {
    return value.__kind__ === "contains" ? {
        contains: value.contains
    } : value.__kind__ === "greaterThan" ? {
        greaterThan: value.greaterThan
    } : value.__kind__ === "equals" ? {
        equals: value.equals
    } : value.__kind__ === "lessThan" ? {
        lessThan: value.lessThan
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "greaterLatitude";
    greaterLatitude: number;
} | {
    __kind__: "greaterLongitude";
    greaterLongitude: number;
} | {
    __kind__: "withinRadius";
    withinRadius: [number, number, number];
} | {
    __kind__: "lessLatitude";
    lessLatitude: number;
} | {
    __kind__: "lessLongitude";
    lessLongitude: number;
}): {
    greaterLatitude: number;
} | {
    greaterLongitude: number;
} | {
    withinRadius: [number, number, number];
} | {
    lessLatitude: number;
} | {
    lessLongitude: number;
} {
    return value.__kind__ === "greaterLatitude" ? {
        greaterLatitude: value.greaterLatitude
    } : value.__kind__ === "greaterLongitude" ? {
        greaterLongitude: value.greaterLongitude
    } : value.__kind__ === "withinRadius" ? {
        withinRadius: value.withinRadius
    } : value.__kind__ === "lessLatitude" ? {
        lessLatitude: value.lessLatitude
    } : value.__kind__ === "lessLongitude" ? {
        lessLongitude: value.lessLongitude
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "greaterThan";
    greaterThan: bigint;
} | {
    __kind__: "equals";
    equals: bigint;
} | {
    __kind__: "lessThan";
    lessThan: bigint;
}): {
    greaterThan: bigint;
} | {
    equals: bigint;
} | {
    lessThan: bigint;
} {
    return value.__kind__ === "greaterThan" ? {
        greaterThan: value.greaterThan
    } : value.__kind__ === "equals" ? {
        equals: value.equals
    } : value.__kind__ === "lessThan" ? {
        lessThan: value.lessThan
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[PartyId, Array<PartyVisitRecord>]>): Array<[_PartyId, Array<_PartyVisitRecord>]> {
    return value.map((x)=>to_candid_tuple_n44(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PartyVisitRecord>): Array<_PartyVisitRecord> {
    return value.map((x)=>to_candid_PartyVisitRecord_n46(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
